main/urls.py
"""The main application's URLs."""
from django.conf.urls import url

from .views import generic
from .views import learn
from .views import webhooks

app_name = "main"
urlpatterns = [
    url(r"^$", generic.home, name="home"),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/$",
        generic.conversation_view,
        name="conversation-view",
    ),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/delete/$",
        generic.conversation_delete,
        name="conversation-delete",
    ),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/change/$",
        generic.conversation_change,
        name="conversation-change",
    ),
]

urlpatterns += [
    url(r"^webhooks/email/$", webhooks.email, name="email-webhook"),
    url(r"^webhooks/cron/$", webhooks.cron, name="cron-webhook"),
]

urlpatterns += [
    url(
        r"^entrary/misc/export-messages/$",
        learn.export_messages,
        name="learn-export-messages",
    )
]

spamnesty/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r"^entrary/", admin.site.urls),
    url(r"^", include("main.urls", namespace="main")),
    url(r"^", include("classification.urls", namespace="classification")),
]


def handler500(request):
    from django.template import loader
    from django.http import HttpResponseServerError

    content_type = request.META.get(
        "HTTP_ACCEPT", request.META.get("CONTENT_TYPE", "text/html")
    ).lower()
    if content_type == "application/json":
        return HttpResponseServerError(
            '{"result": "error", "error_msg": "There was a server error. Please try again later."}',
            content_type="application/json",
        )

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render(context={}, request=request))

main/views/generic.py
from annoying.decorators import render_to
from django.conf import settings
from django.contrib import messages
from django.core.cache import cache
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import OuterRef
from django.db.models import Subquery
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.utils.crypto import constant_time_compare
from django.views.decorators.http import require_POST

from ..models import Conversation
from ..models import Message
from ..models import SpamCategory


@render_to("home.html")
def home(request):
    if not (request.get_host().startswith("spa.") or settings.DEBUG):
        return {"TEMPLATE": "fake.html"}

    # Prepare a subquery of the most recent sent message in every conversation.
    newest = Message.objects.filter(
        direction="S", conversation=OuterRef("pk")
    ).order_by("-timestamp")

    # Retrieve conversations, ordering them by the most recent sent message from the subquery.
    conversations = cache.get("conversations")
    if not conversations:
        conversations = (
            Conversation.objects.annotate(
                last_message_time=Subquery(newest.values("timestamp")[:1]),
                num_messages=Count("message"),
            )
            .filter(num_messages__gt=15, num_messages__lt=50)
            .order_by("-last_message_time")
        )
        cache.set("conversations", list(conversations), 12 * 60 * 60)

    paginator = Paginator(conversations, 50)
    page = request.GET.get("page")
    try:
        conversations = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        conversations = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        conversations = paginator.page(paginator.num_pages)

    return {"conversations": conversations}


@require_POST
def conversation_delete(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    if (
        constant_time_compare(request.GET.get("key"), conversation.secret_key)
        or request.user.is_staff
    ):
        messages.success(request, "The conversation has been deleted.")
        conversation.delete()
    else:
        messages.error(request, "The conversation's secret key was invalid.")
    return redirect("main:home")


def conversation_change(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    category = get_object_or_404(SpamCategory, pk=request.GET.get("category", ""))
    if (
        constant_time_compare(request.GET.get("key"), conversation.secret_key)
        or request.user.is_staff
    ):
        messages.success(request, "The conversation's category has been changed.")
        conversation.category = category
        conversation.classified = request.user.is_staff
        conversation.save()
    else:
        messages.error(request, "The conversation's secret key was invalid.")
    return redirect(conversation)


@render_to("conversation_view.html")
def conversation_view(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    own_conversation = constant_time_compare(
        request.GET.get("key"), conversation.secret_key
    )

    if own_conversation and "@" in conversation.reporter_email:
        other_conversations = (
            Conversation.objects.filter(reporter_email=conversation.reporter_email)
            .annotate(num_messages=Count("message"))
            .order_by("-num_messages", "-created")
        )
    else:
        other_conversations = []

    # Sort with the default category being last.
    categories = SpamCategory.objects.order_by("default", "name")
    return {
        "conversation": conversation,
        "own": own_conversation,
        "spam_categories": categories,
        "other_conversations": other_conversations,
    }

main/views/learn.py
"""ML-related views."""
import json

from django.contrib.auth.decorators import user_passes_test
from django.db.models import Count
from django.http import StreamingHttpResponse

from main.models import Conversation
from main.models import SpamCategory


def message_exporter():
    # We need to do these contortions so we can stream the response.
    yield '{"categories": '
    yield json.dumps(
        [{"id": cat.id, "name": cat.name} for cat in SpamCategory.objects.all()],
        indent=2,
    ) + ', "messages": ['

    for counter, conversation in enumerate(
        Conversation.objects.annotate(num_messages=Count("message")).filter(
            num_messages__gte=1
        )
    ):
        yield "," if counter else ""
        message = conversation.messages[0]
        message_exp = {
            "message_id": message.message_id,
            "subject": message.subject,
            "body": message.best_body,
            "category": conversation.category_id,
            "classified": conversation.classified,
        }
        yield json.dumps(message_exp, indent=2, sort_keys=True)
    yield "]}"


@user_passes_test(lambda u: u.is_superuser)
def export_messages(request):
    """Export spam messages as a JSON object."""
    response = StreamingHttpResponse(
        message_exporter(), content_type="application/json"
    )
    response["Content-Disposition"] = 'attachment; filename="spamnesty_messages.json"'
    return response

main/views/webhooks.py
import json
import re

from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from raven.contrib.django.raven_compat.models import client

from ..models import Message
from ..utils import check_last_messages_similarity
from ..utils import construct_reply


def process_forwarded_email(request):
    """Perform necessary tasks when a user forwards a legitimate email."""
    from_addr = request.POST.get("addresses[from]")
    if not from_addr:
        return HttpResponse("Empty sender.")

    if Message.objects.filter(message_id=request.POST.get("id", "")).exists():
        # Ignore webhook retries if we've already added the message.
        return HttpResponse("OK")

    # Try to parse the forwarded message.
    try:
        message = Message.parse_from_webhook(request.POST, forwarded=True)
    except Exception:
        # Notify Sentry.
        client.captureException()
        message = None

    if not message:
        print(json.dumps(request.POST))
        # Notify the sender that we couldn't find the spammer's address.
        EmailMessage(
            subject=render_to_string(
                "emails/forward_no_email_subject.txt", request=request
            ).strip(),
            body=render_to_string("emails/forward_no_email_body.txt", request=request),
            to=[from_addr],
        ).send()
    else:
        # Notify the sender that we've received it.
        EmailMessage(
            subject=render_to_string(
                "emails/forward_received_subject.txt", request=request
            ).strip(),
            body=render_to_string(
                "emails/forward_received_body.txt",
                context={"message": message},
                request=request,
            ),
            to=[from_addr],
        ).send()

        # Reply to the spammer.
        reply = construct_reply(message)
        reply.send()


def process_spam(request):
    """Perform necessary tasks when we get some email."""
    # Parse the received message.
    message = Message.parse_from_webhook(request.POST)

    # If there is no unsent message in the queue, queue one.
    if (
        message
        and message.conversation.messages.count() <= 40
        and not check_last_messages_similarity(message.conversation)
        and not message.conversation.messages.exclude(send_on=None).exists()
    ):
        # Reply to the spammer.
        reply = construct_reply(message)
        reply.queue()


@csrf_exempt
def email(request):
    if "id" in request.POST:
        if re.search(
            r"spa?@mnesty\.com", request.POST.get("addresses[to]", "").lower()
        ):
            process_forwarded_email(request)
        else:
            process_spam(request)
    return HttpResponse("OK")


@csrf_exempt
def cron(request):
    """Send unsent emails."""
    Message.send_unsent()
    return HttpResponse("OK")

main/templates/base.html
{% load staticfiles bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ request.site.name }} - {% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" crossorigin="anonymous">

        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block scripts %}
        {% endblock %}
    </head>
    <body>
        {% if not settings.DEBUG %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-51110-28', 'auto');
            ga('send', 'pageview');

        </script>
        {% endif %}

        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">{{ request.site.name }}</a>
                <p class="navbar-text">Fun with spam!</p>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if other_conversations %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your conversations <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for conversation in other_conversations %}
                        <li>
                        <a href="{% url "main:conversation-view" conversation.id %}">The colloquy of {{ conversation.sender_name }} ({{ conversation.num_messages }})</a>
                        </li>
                        {% endfor %}
                    </ul>
                    </li>
                    {% endif %}

                    {% if request.user.is_authenticated %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "admin:index" %}">Admin</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url "admin:logout" %}">Logout</a></li>
                    </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        </nav>

        <div class="container">
            {% bootstrap_messages %}

            {% block content %}
            {% endblock %}
        </div>

        <!-- {{ settings.COMMIT_HASH }} -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/conversation_view.html
{% extends "base.html" %}

{% block title %}The colloquy of {{ conversation.sender_name }}{% endblock %}

{% block scripts %}
<meta name="robots" content="noindex">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>The colloquy of {{ conversation.sender_name }}</h3>
        <p>
        Someone forwarded a spammer's email to {{ request.site.name }}, which
        replied to the email, pretending to be a person called
        {{ conversation.sender_name }} and starting a conversation.
        </p>

        <p>
        This is that conversation.
        </p>

        {% if request.user.is_staff %}
        <a class="btn btn-default" href="{% url "admin:main_conversation_change" conversation.id %}">Admin</a>
        {% endif %}

        {% if own or request.user.is_staff %}
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ conversation.category }} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li class="disabled"><a href="#">Select the category of the spam email</a></li>
                <li role="separator" class="divider"></li>
                {% for category in spam_categories %}
                <li><a href="{% url "main:conversation-change" conversation.id %}?key={{ request.GET.key }}&category={{ category.id }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <form method="POST" style="display: inline" action="{% url "main:conversation-delete" conversation.id %}?key={{ request.GET.key }}">{% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        {% endif %}
    </div>
    <div class="col-md-12">
        <hr>
    </div>
</div>

{% for message in conversation.message_set.all %}
    <div class="row">
        {% if message.direction == "S" %}
        <div class="col-md-4"></div>
        {% endif %}

        <div class="col-md-8">
            {% if message.direction == "S" %}
            <div class="panel panel-default panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ request.site.name }}</h3>

            {% else %}
            <div class="panel panel-default panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Spammer</h3>
            {% endif %}
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>Subject:</strong> {{ message.subject }}</li>
                    <li class="list-group-item"><strong>On:</strong> {{ message.timestamp }}</li>
                </ul>
                <div class="panel-body">
                    <p>{{ message.best_body|linebreaks }}</p>
                </div>
            </div>
        </div>

        {% if message.direction != "S" %}
        <div class="col-md-4"></div>
        {% endif %}
    </div>
{% endfor %}
</div>
{% endblock %}

main/templates/fake.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Welcome to the web presence of MNesty, LLC</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/55291a2f3d.js"></script>

		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
        <style>
            /* -- custom css for Bootstrap 3.x --*/

            /* move special fonts to HTML head for better performance */
            @import url(https://fonts.googleapis.com/css?family=Voltaire);

            html,
            body {
                height: 100%;
                width: 100%;
                font-family:Arial,sans-serif;
            }

            /* fix bs3 horizontal scrollbar bug */
            .row { margin: 0; padding: 0 }


            /* use special fonts in certain elements */
            h1,h2,h3,h4,.lead,.btn,.navbar a {
                text-transform:uppercase;
                font-family:'Voltaire',Arial,sans-serif;
                letter-spacing:2px;
            }

            h1 {
                font-size:50px;
            }

            /* make images gray */
            img.grayscale {
                filter: url("data:image/svg+xml;utf8,<svg xmlns=\'https://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale"); /* Firefox 10+, Firefox on Android */
                filter: gray; /* IE6-9 */
                -webkit-filter: grayscale(100%); /* Chrome 19+, Safari 6+, Safari 6+ iOS */
            }

            .icon-bar {
                background-color:#fff;
            }

            .scroll-down a, .scroll-top a {
                color:#ffffff;
            }

            .scroll-down {
                position:fixed;
                bottom:20%;
                right:0%;
                color:#f9f9f9;
            }

            .scroll-top {
                background-color:#dbdbdb;
            }

            .vert {
                vertical-align: middle;
                width:100%;
                padding-top:4%;
                text-align:center;
            }

            .header .btn-lg {
                font-size:28px;
                border-color:#eeeeee;
                padding:15px;
                background-color:transparent;
                color:#ffffff;
            }

            .header .btn-lg:hover {
                background-color:#eeeeee;
                color:#777777;
            }

            .navbar a {
                color:#fff;
                font-size:14px;
            }

            .navbar-bold.affix {
                background-color:#d46054;
            }

            .navbar-bold {
                background-color:#f68076;
                font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
            }

            .navbar-bold li a:hover, .navbar-bold li.active {
                background-color:#d46054;
            }


            .header h1 {
                font-size:80px;
                -webkit-text-stroke: 1px rgba(f,f,f,0.1);
                color:#431a6d;
                color:#fff;
                margin-left:-5px;
                margin-bottom:5px;
                text-transform:uppercase;
            }

            .header .lead {
                color:#d46054;
                font-size:25px;
            }

            .header {
                height: 40%;
                background: #f68076 url('{% static "images/hero.jpg" %}') center;
                background-size: cover;
                min-height: 600px;
            }

            /* use alt in navbar and header for different color */

            .alt {
                background-color: #6E28C9;
            }

            .alt .lead {
                color: #3B0496;
            }

            .alt.affix {
                background-color:#4C06AB;
            }

            .alt li a:hover, .alt li.active {
                background-color:#5D17BA;
            }



            .blurb {
                padding: 120px 0;
                background-color:#fefefe;
            }

            .blurb .panel {
                background-color:transparent;
            }

            .bright {
                background: #dbdbdb url('../assets/pt_topo.png') repeat center center fixed;
                color:#777;
            }

            .featurette {
                background: #222334;
                padding: 50px 0;
                color: #ffffff;
            }

            .featurette-item {
                margin-bottom: 15px;
            }

            .featurette-item > i {
                border: 3px solid #ffffff;
                border-radius: 50%;
                display: inline-block;
                font-size: 56px;
                width: 140px;
                height: 140px;
                line-height: 136px;
                vertical-align: middle;
                text-align: center;
            }

            .featurette-item > i:hover {
                font-size: 68px;
            }

            .callout {
                color: #ffffff;
                padding-top:7%;
                height: 100%;
                width: 100%;
                background: url('../assets/bg_suburb.jpg') no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }

            .gallery {
                padding: 50px 0;
            }

            .call-to-action {
                background: #eeeeee;
                padding: 50px 0;
            }

            .call-to-action .btn {
                margin: 10px;
            }

            footer {
                padding: 100px 0;
            }

            /* -- end custom css for Bootstrap 3.x --*/
        </style>
	</head>
	<body>

	<nav class="navbar navbar-fixed-top alt" data-spy="affix" data-offset-top="1000">
	  <div class="container">
		<div class="navbar-header">
		  <a href="#" class="navbar-brand">Home</a>
		  <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </a>
		</div>

		<div class="navbar-collapse collapse" id="navbar">
		  <ul class="nav navbar-nav">
			<li><a href="#sec1">Your shipment</a></li>
			<li><a href="#sec2">Features</a></li>
			<li><a href="#sec3">Contact</a></li>
		  </ul>
		</div>
	   </div>
	</nav>

    <div class="header alt vert">
        <div class="container">
            <p>&nbsp;<br/>&nbsp;</p>

            <h1>MNesty, LLC</h1>
            <p class="lead">Asia's premier maritime logistics company,<br/> strategically located in Mongolia.</p>
        </div>
    </div>

	<div id="sec1" class="blurb">
	  <div class="container">
		<div class="row">
		  <div class="col-md-7">
			<h1>Your shipment, the world over</h1>
			<p class="lead">We handle every port globally</p>
		  </div>
		  <div class="col-md-5">
			<h1 class="pull-right"><i class="fa fa-globe fa-3x"></i> <i class="fa fa-ship fa-3x"></i></h1>
		  </div>
		</div>
	  </div>
	</div>

	<div class="featurette" id="sec2">
	  <div class="container">
		<div class="row">
		  <div class="col-md-12 text-center">
			<h1>Security, affordability, promptness</h1>
		  </div>
		</div>
		<div class="row">
		  <div class="col-md-2 col-md-offset-2 text-center">
			<div class="featurette-item">
			  <i class="fa fa-lock"></i>
			  <h4>Security</h4>
			  <p>Every shipment is insured.</p>
			</div>
		  </div>
		  <div class="col-md-2 text-center">
			<div class="featurette-item">
			  <i class="fa fa-dollar"></i>
			  <h4>Affordability</h4>
			  <p>Global reach for local cost.</p>
			</div>
		  </div>
		  <div class="col-md-2 text-center">
			<div class="featurette-item">
			  <i class="fa fa-clock-o"></i>
			  <h4>Promptness</h4>
			  <p>Your shipment, on time.</p>
			</div>
		  </div>
		  <div class="col-md-2 text-center">
			<div class="featurette-item">
			  <i class="fa fa-phone"></i>
			  <h4>Outreach</h4>
			  <p>Contact us today.</p>
			</div>
		  </div>
		</div>
	  </div>
	</div>

	<footer>
	  <div class="container" id="sec3">
		<div class="row">
		  <div class="col-md-6 col-md-offset-3 text-center">
			<ul class="list-inline">
			  <li><i class="fa fa-facebook fa fa-2x"></i></li>
			  <li><i class="fa fa-twitter fa fa-2x"></i></li>
			  <li><i class="fa fa-google-plus fa fa-2x"></i></li>
			  <li><i class="fa fa-pinterest fa fa-2x"></i></li>
			</ul>
			<hr>
            <p>Looking for amnesty? <a href="https://spa.mnesty.com/">Look no further</a>.</p>
		  </div>
		</div>
	  </div>
	</footer>

	<ul class="nav pull-right scroll-down">
	  <li><a href="#" title="Scroll down"><i class="fa fa-chevron-down fa fa-3x"></i></a></li>
	</ul>
	<ul class="nav pull-right scroll-top">
	  <li><a href="#" title="Scroll to top"><i class="fa fa-chevron-up fa fa-3x"></i></a></li>
	</ul>

	<!-- script references -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script>
            $(document).ready(function(){/* smooth scrolling for scroll to top */
                $('.scroll-top').click(function(){
                    $('body,html').animate({scrollTop:0},800);
                })
                /* smooth scrolling for scroll down */
                $('.scroll-down').click(function(){
                    $('body,html').animate({scrollTop:$(window).scrollTop()+800},1000);
                })

                /* highlight the top nav as scrolling occurs */
                $('body').scrollspy({ target: '#navbar' })

            });
        </script>
	</body>
</html>

main/templates/home.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h2>What is {{ request.site.name }}?</h2>
        <p>{{ request.site.name }} is a way to waste spammers' time. If you get a spam
        email, simply forward it to <strong>sp@mnesty.com</strong>,
        and {{ request.site.name }} will strip your email address, pretend it's a real
        person and reply to the email. Just remember to strip out any personal
        information from the body of the email, as it will be used so the reply looks
        more legitimate.</p>

        <p>That way, the spammer will start talking to a bot, and hopefully waste some
        time there instead of spending it on a real victim. Meanwhile,
        {{ request.site.name }} will send you an email with a link to the conversation,
        so you can watch it unfold live!</p>

        <h3>Current state</h3>
        <p>
        <span style="float:right; padding-left: 10px">
        <script src="https://liberapay.com/Spamnesty/widgets/receiving.js"></script>
        </span>
        <strong>WARNING:</strong> The service isn't done yet! It looks like crap and
        there may be loads of wonky stuff going on. That said, you can help by
        cautiously using it for a bit, and
        <a href="https://gitlab.com/stavros/Spamnesty/issues">opening an issue</a>
        if you notice something wrong or if you have any suggestions.
        <p>

        <p>
        Also, it turns out email is expensive. Please donate to keep the service
        running! Big thanks go to <a href="https://elasticemail.com/" target="_blank">ElasticEmail</a>, which handles
        our email sending for us.
        </p>

        <p>
        Thanks for your help!
        </p>

        <p>
        <a class="btn btn-primary" href="https://gitlab.com/stavros/Spamnesty">
            <i class="fa fa-code-fork"></i>
            Fork me on Gitlab
        </a>
        </p>

        <h3>Conversations</h3>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Person</th>
                        <th>Subject</th>
                        <th>Date</th>
                        <th>Msgs</th>
                    </tr>


                    {% for conversation in conversations.object_list %}
                    <tr>
                        <td><a href="{% url "main:conversation-view" conversation.id %}">{{ conversation.sender_name }}</a></td>
                        <td>{{ conversation.message_set.first.subject }}</td>
                        <td>{{ conversation.last_message_time|date:"d M Y" }}</td>
                        <td>{{ conversation.num_messages}}</td>
                    </tr>
                    {% endfor %}
                </table>
                {% bootstrap_pagination conversations pages_to_show=6 %}
            </div>
        </div>
    </div>
</div>
{% endblock %}