classification/urls.py
from django.conf.urls import url

from .views import classify
from .views import delete_conversation

app_name = "classification"
urlpatterns = [
    url(r"^classify/$", classify, name="classify"),
    url(r"^delete/$", delete_conversation, name="delete"),
]

main/urls.py
"""The main application's URLs."""
from django.conf.urls import url

from .views import generic
from .views import learn
from .views import webhooks

app_name = "main"
urlpatterns = [
    url(r"^$", generic.home, name="home"),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/$",
        generic.conversation_view,
        name="conversation-view",
    ),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/delete/$",
        generic.conversation_delete,
        name="conversation-delete",
    ),
    url(
        r"^conversations/(?P<conversation_id>[^/]*)/change/$",
        generic.conversation_change,
        name="conversation-change",
    ),
]

urlpatterns += [
    url(r"^webhooks/email/$", webhooks.email, name="email-webhook"),
    url(r"^webhooks/cron/$", webhooks.cron, name="cron-webhook"),
]

urlpatterns += [
    url(
        r"^entrary/misc/export-messages/$",
        learn.export_messages,
        name="learn-export-messages",
    )
]

spamnesty/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r"^entrary/", admin.site.urls),
    url(r"^", include("main.urls", namespace="main")),
    url(r"^", include("classification.urls", namespace="classification")),
]


def handler500(request):
    from django.template import loader
    from django.http import HttpResponseServerError

    content_type = request.META.get(
        "HTTP_ACCEPT", request.META.get("CONTENT_TYPE", "text/html")
    ).lower()
    if content_type == "application/json":
        return HttpResponseServerError(
            '{"result": "error", "error_msg": "There was a server error. Please try again later."}',
            content_type="application/json",
        )

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render(context={}, request=request))

classification/views.py
from annoying.decorators import render_to
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods

from main.models import Conversation
from main.models import SpamCategory


@staff_member_required
@require_http_methods(["GET", "POST"])
@render_to("classify.html")
def classify(request):
    """Allow staff to classify conversations into categories."""
    if request.method == "POST":
        conversation = get_object_or_404(
            Conversation, pk=request.POST.get("conversation_id")
        )
        category = get_object_or_404(
            SpamCategory, pk=request.POST.get("category_id", "")
        )
        conversation.category = category
        conversation.classified = True
        conversation.save()
        return {"result": "success"}
    else:
        conversations = Conversation.objects.filter(classified=False)
        conv_count = Conversation.objects.count()
        progress = (
            int((100.0 * conversations.count()) / conv_count) if conv_count else 100
        )

        categories = SpamCategory.objects.all()
        return {
            "conversations": conversations[:10],
            "spam_categories": categories,
            "progress": 100 - progress,
        }


@staff_member_required
@require_http_methods(["POST"])
@render_to("classify.html")
def delete_conversation(request):
    """Allow staff to delete conversations."""
    conversation = get_object_or_404(
        Conversation, pk=request.POST.get("conversation_id")
    )
    conversation.delete()
    return {"result": "success"}

classification/templates/classify.html
{% extends "base.html" %}

{% block title %}Conversation classification{% endblock %}

{% block scripts %}
<script>
function classifyConversation(conversation_id, category_id) {
    var data = new FormData();
    if(category_id === null) {
        category_id = jQuery('#conv-id-'+conversation_id+' .category-button').attr('spamcat')
    }
    category_name = jQuery('#conv-id-'+conversation_id+' .cat-'+category_id+' a').text()
    data.append('conversation_id', conversation_id);
    data.append('category_id', category_id);
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

    var xhr = new XMLHttpRequest();
    xhr.conv_id = conversation_id;
    xhr.open('POST', '{% url "classification:classify" %}', true);
    xhr.onload = function () {
        jQuery('#conv-id-'+this.conv_id).addClass('classified')
        jQuery('#conv-id-'+this.conv_id+' button.category-button').text(category_name)
        jQuery('#conv-id-'+this.conv_id+' .category-button').attr('spamcat', category_id)
        jQuery('#conv-id-'+this.conv_id+' .classified-mark').fadeTo(500, 1.0).delay(2000).fadeTo(1000, 0.0)
    };
    xhr.send(data);
}
function deleteConversation(conversation_id) {
    var data = new FormData();
    data.append('conversation_id', conversation_id);
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

    var xhr = new XMLHttpRequest();
    xhr.conv_id = conversation_id;
    xhr.open('POST', '{% url "classification:delete" %}', true);
    xhr.onload = function () {
        jQuery('#conv-id-'+this.conv_id+' td').addClass('deleted')
        jQuery('#conv-id-'+this.conv_id+' .conv-buttons').addClass('deleted')
    };
    xhr.send(data);
}

</script>
{% endblock %}

{% block content %}
<div class="row">

    <div class="col-xs-12">
        <h2>Classify conversations</h2>
        <p>
        Please select the appropriate category for each conversation. You can
        change a conversation's classifications, but if you reload the page
        after classifying, the conversation won't show up. So, double-check that
        you've picked the correct category before navigating away.
        </p>

        <div class="progress">
            <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%">
                <span class="sr-only">20% Complete</span>
            </div>
        </div>

        <table class="table">
            <tr>
                <th>Message</th>
                <th>Actions</th>
            </tr>

            {% for conversation in conversations %}
            <tr id='conv-id-{{ conversation.id }}'>
                <td class='conv-body'>{{ conversation.messages.first.best_body|linebreaksbr }}</td>
                <td class='conv-buttons'>
                    {% if request.user.is_staff %}
                    <p><a class="btn btn-danger" href="{% url "admin:main_conversation_change" conversation.id %}">Admin</a></p>
                    <p><a class="btn btn-danger" href="#" onclick="deleteConversation('{{ conversation.id }}'); return false;">Delete</a></p>
                    {% endif %}

                    <div class="btn-group">
                        <button type="button" class="btn btn-primary category-button" spamcat="{{ conversation.category_id }}"  onclick="classifyConversation('{{ conversation.id }}', null); return false;">{{ conversation.category }}</button>
                        <button type="button" class="btn btn-primary dropdown-toggle conv-{{ conversation.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button><i class="classified-mark fa fa-check" aria-hidden="true"></i>
                        <ul class="dropdown-menu">
                            <li class="disabled"><a href="#">Select the category of the spam email</a></li>
                            <li role="separator" class="divider"></li>
                            {% for category in spam_categories %}
                            <li class="cat-{{ category.id }}"><a href="#" onclick="classifyConversation('{{ conversation.id }}', '{{ category.id }}'); return false;">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}